fix: Killercoda new issue link redirect correction
afzal442/keptn-pg-killerway pull request #75
Opened 2023-02-09 17:41 UTC by SuperAayush

The final page link to new issue creation in killercoda demo is updated from the GitHub homepage to [here](https://github.com/afzal442/keptn-pg-killerway/issues/new).

Issue Link - https://github.com/keptn/keptn/issues/9502

2023-02-09 23:52 UTC, agardnerIT submitted a review, later dismissed

2023-02-09 23:53 UTC, agardnerIT requested changes
Please review the link syntax. This is incorrect.

2023-02-10 08:34 UTC, SuperAayush commented
Sorry, my bad didn't double-check before committing, I hope it is fixed now!!

cc- @agardnerIT

2023-02-16 21:32 UTC, agardnerIT approved these changes

2023-02-16 21:32 UTC, merged